{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "python.fullname" . }}
  labels:
    {{- include "python.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
    host: {{ .Values.route.host | quote }}
    path: {{ .Values.route.path | quote }}
    to:
      kind: Service
      name: {{ include "python.fullname" $ }}
    port:
      targetPort: {{ $.Values.service.port }}
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
{{- end }}
